### ISSUE TITLE
Repeatable app crash (recovered from the logs) when "Stopping" a timer

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#44]
ERROR: Unhandled Exception
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:57)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:57)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Invalid Resource Specified
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  T:\TVM\api\WatchUi.mb (setBitmap:1435)
  T:\TVM\api\WatchUi.mb (initialize:1355)
  Rez (WelcomeLayout:19)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Invalid Resource Specified
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  T:\TVM\api\WatchUi.mb (setBitmap:1435)
  T:\TVM\api\WatchUi.mb (initialize:1355)
  Rez (WelcomeLayout:19)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: System Error
DETAILS: 
STORE_ID: bfbcb162f21549cb8185dad7e6dc4595
CALLSTACK:
	@PC = 0x1000034c
	@PC = 0x10001497
	@PC = 0x10001248

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:105)
  /Users/canedo/eclipse-workspace/barbecue_app/source/WelcomeView.mc (onLayout:14)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

**Comment by nilsbenson** [comment]
is there any detail in the crash report about which device(s) this happened on? 

My guess is that since the release version only has fenix-6 and the base FR235 layouts that it's possible one of the devices that's not directly supported was used and there was a resource problem.

**Comment by arquicanedo** [comment]
Sorry my bad for not being explicit. This happened on my fr235 on the **development** version. However, I think it was one of those random watch hiccups.

**Comment by arquicanedo** [comment]
Will stress the app today during the grilling session later. Will go crazy on it and see if there are other crashes like this. It happened yesterday and I just recovered the logs.

**Comment by arquicanedo** [comment]
Whenever stop is selected it crashes on fr235. Will investigate.

Latest log.

ERROR: Unhandled Exception
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: Circular Dependency Error
DETAILS: 
STORE_ID: 030305743c6e484a9bd8ce2ca0249651
CALLSTACK:
	@PC = 0x100039e2
	@PC = 0x10000405
	@PC = 0x1000033d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:57)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:57)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Invalid Resource Specified
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  T:\TVM\api\WatchUi.mb (setBitmap:1435)
  T:\TVM\api\WatchUi.mb (initialize:1355)
  Rez (WelcomeLayout:19)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: Invalid Resource Specified
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  T:\TVM\api\WatchUi.mb (setBitmap:1435)
  T:\TVM\api\WatchUi.mb (initialize:1355)
  Rez (WelcomeLayout:19)
  /Users/canedo/eclipse-workspace/barbecue_app/source/welcomeView.mc (onLayout:14)

ERROR: System Error
DETAILS: 
STORE_ID: bfbcb162f21549cb8185dad7e6dc4595
CALLSTACK:
	@PC = 0x1000034c
	@PC = 0x10001497
	@PC = 0x10001248

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: System Error
DETAILS: 
STORE_ID: 08760e1e16c74a61ab0c6c4a9b632b3f
CALLSTACK:
	@PC = 0x100000c6
	@PC = 0x1000003d

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  Rez (initialize:105)
  /Users/canedo/eclipse-workspace/barbecue_app/source/WelcomeView.mc (onLayout:14)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

ERROR: Symbol Not Found Error
DETAILS: 
STORE_ID: 00000000000000000000000000000000
CALLSTACK:
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onSelect:29)
  /Users/canedo/eclipse-workspace/barbecue_app/source/MenuDelegate.mc (onMenuItem:17)

**Comment by nilsbenson** [comment]
do a pull and try that. there was a typo in the menu layout that I fixed which may or may not be involved

**Comment by arquicanedo** [comment]
I noticed the timerMenu44 in parallel to your commit but that doesn't fix the bug. Continues to crash. I'll spend some time on this.

**Comment by nilsbenson** [comment]
![image](https://user-images.githubusercontent.com/814623/83978179-5b313380-a8cb-11ea-9a04-40abdd44fc78.png)

"item" might be null for some reason and the missing symbol error might be because of the .toString(). 

If it is null, we may consider that's the best case option is stopping the timer (which both "fixes" the bug, and keeps the "expected" behavior).

**Comment by arquicanedo** [comment]
I had commented out the println, but I agree with your conditions and outcomes. I'll test and push the patch if it fixes it.

**Comment by arquicanedo** [comment]
When it crashes it is not because it is null but because item does not have a toString method. To whatever this is set to. I also tried wrapping the println in a try/catch. I'm commenting this println for now.
